package services

////////////////////////////////////////////////////////////////////////////////
// Do not modify this file, it is automatically generated
////////////////////////////////////////////////////////////////////////////////

type ColorName int

const (
	ColorNamealiceblue ColorName = iota
	ColorNameantiquewhite
	ColorNameaqua
	ColorNameaquamarine
	ColorNameazure
	ColorNamebeige
	ColorNamebisque
	ColorNameblanchedalmond
	ColorNameblue
	ColorNameblueviolet
	ColorNamebrown
	ColorNameburlywood
	ColorNamecadetblue
	ColorNamechartreuse
	ColorNamechocolate
	ColorNamecoral
	ColorNamecornflowerblue
	ColorNamecornsilk
	ColorNamecrimson
	ColorNamecyan
	ColorNamedarkblue
	ColorNamedarkcyan
	ColorNamedarkgoldenrod
	ColorNamedarkgray
	ColorNamedarkgreen
	ColorNamedarkgrey
	ColorNamedarkkhaki
	ColorNamedarkmagenta
	ColorNamedarkolivegreen
	ColorNamedarkorange
	ColorNamedarkorchid
	ColorNamedarkred
	ColorNamedarksalmon
	ColorNamedarkseagreen
	ColorNamedarkslateblue
	ColorNamedarkslategray
	ColorNamedarkslategrey
	ColorNamedarkturquoise
	ColorNamedarkviolet
	ColorNamedeeppink
	ColorNamedeepskyblue
	ColorNamedimgray
	ColorNamedimgrey
	ColorNamedodgerblue
	ColorNamefirebrick
	ColorNamefloralwhite
	ColorNameforestgreen
	ColorNamefuchsia
	ColorNamegainsboro
	ColorNameghostwhite
	ColorNamegold
	ColorNamegoldenrod
	ColorNamegray
	ColorNamegreen
	ColorNamegreenyellow
	ColorNamegrey
	ColorNamehomeassistant
	ColorNamehoneydew
	ColorNamehotpink
	ColorNameindianred
	ColorNameindigo
	ColorNameivory
	ColorNamekhaki
	ColorNamelavender
	ColorNamelavenderblush
	ColorNamelawngreen
	ColorNamelemonchiffon
	ColorNamelightblue
	ColorNamelightcoral
	ColorNamelightcyan
	ColorNamelightgoldenrodyellow
	ColorNamelightgray
	ColorNamelightgreen
	ColorNamelightgrey
	ColorNamelightpink
	ColorNamelightsalmon
	ColorNamelightseagreen
	ColorNamelightskyblue
	ColorNamelightslategray
	ColorNamelightslategrey
	ColorNamelightsteelblue
	ColorNamelightyellow
	ColorNamelime
	ColorNamelimegreen
	ColorNamelinen
	ColorNamemagenta
	ColorNamemaroon
	ColorNamemediumaquamarine
	ColorNamemediumblue
	ColorNamemediumorchid
	ColorNamemediumpurple
	ColorNamemediumseagreen
	ColorNamemediumslateblue
	ColorNamemediumspringgreen
	ColorNamemediumturquoise
	ColorNamemediumvioletred
	ColorNamemidnightblue
	ColorNamemintcream
	ColorNamemistyrose
	ColorNamemoccasin
	ColorNamenavajowhite
	ColorNamenavy
	ColorNamenavyblue
	ColorNameoldlace
	ColorNameolive
	ColorNameolivedrab
	ColorNameorange
	ColorNameorangered
	ColorNameorchid
	ColorNamepalegoldenrod
	ColorNamepalegreen
	ColorNamepaleturquoise
	ColorNamepalevioletred
	ColorNamepapayawhip
	ColorNamepeachpuff
	ColorNameperu
	ColorNamepink
	ColorNameplum
	ColorNamepowderblue
	ColorNamepurple
	ColorNamered
	ColorNamerosybrown
	ColorNameroyalblue
	ColorNamesaddlebrown
	ColorNamesalmon
	ColorNamesandybrown
	ColorNameseagreen
	ColorNameseashell
	ColorNamesienna
	ColorNamesilver
	ColorNameskyblue
	ColorNameslateblue
	ColorNameslategray
	ColorNameslategrey
	ColorNamesnow
	ColorNamespringgreen
	ColorNamesteelblue
	ColorNametan
	ColorNameteal
	ColorNamethistle
	ColorNametomato
	ColorNameturquoise
	ColorNameviolet
	ColorNamewheat
	ColorNamewhite
	ColorNamewhitesmoke
	ColorNameyellow
	ColorNameyellowgreen
)
