// Code generated by "stringer -type=Direction -trimprefix=Direction"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Directionforward-0]
	_ = x[Directionreverse-1]
}

const _Direction_name = "forwardreverse"

var _Direction_index = [...]uint8{0, 7, 14}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
