// Code generated by "stringer -type=Flash -trimprefix=Flash"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Flashlong-0]
	_ = x[Flashshort-1]
}

const _Flash_name = "longshort"

var _Flash_index = [...]uint8{0, 4, 9}

func (i Flash) String() string {
	if i < 0 || i >= Flash(len(_Flash_index)-1) {
		return "Flash(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Flash_name[_Flash_index[i]:_Flash_index[i+1]]
}
