// Code generated by jsonenums -type=Format; DO NOT EDIT.

package services

import (
	"fmt"
	"github.com/goccy/go-json"
)

var (
	_FormatNameToValue = map[string]Format{
		"Formathls": Formathls,
	}

	_FormatValueToName = map[Format]string{
		Formathls: "Formathls",
	}
)

func init() {
	var v Format
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_FormatNameToValue = map[string]Format{
			interface{}(Formathls).(fmt.Stringer).String(): Formathls,
		}
	}
}

// MarshalJSON is generated so Format satisfies json.Marshaler.
func (r Format) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _FormatValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Format: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Format satisfies json.Unmarshaler.
func (r *Format) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Format should be a string, got %s", data)
	}
	v, ok := _FormatNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Format %q", s)
	}
	*r = v
	return nil
}
