// Code generated by "stringer -type=HvacMode -trimprefix=HvacMode"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HvacModeauto-0]
	_ = x[HvacModecool-1]
	_ = x[HvacModedry-2]
	_ = x[HvacModefan_only-3]
	_ = x[HvacModeheat-4]
	_ = x[HvacModeheat_cool-5]
	_ = x[HvacModeoff-6]
}

const _HvacMode_name = "autocooldryfan_onlyheatheat_cooloff"

var _HvacMode_index = [...]uint8{0, 4, 8, 11, 19, 23, 32, 35}

func (i HvacMode) String() string {
	if i < 0 || i >= HvacMode(len(_HvacMode_index)-1) {
		return "HvacMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HvacMode_name[_HvacMode_index[i]:_HvacMode_index[i+1]]
}
