// Code generated by "stringer -type=Level -trimprefix=Level"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Levelcritical-0]
	_ = x[Leveldebug-1]
	_ = x[Levelerror-2]
	_ = x[Levelfatal-3]
	_ = x[Levelinfo-4]
	_ = x[Levelwarning-5]
}

const _Level_name = "criticaldebugerrorfatalinfowarning"

var _Level_index = [...]uint8{0, 8, 13, 18, 23, 27, 34}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
