// Code generated by "stringer -type=Qos -trimprefix=Qos"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Qos0-0]
	_ = x[Qos1-1]
	_ = x[Qos2-2]
}

const _Qos_name = "012"

var _Qos_index = [...]uint8{0, 1, 2, 3}

func (i Qos) String() string {
	if i < 0 || i >= Qos(len(_Qos_index)-1) {
		return "Qos(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Qos_name[_Qos_index[i]:_Qos_index[i+1]]
}
