// Code generated by "stringer -type=RepeatType -trimprefix=RepeatType"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RepeatTypepause-0]
	_ = x[RepeatTyperepeat-1]
	_ = x[RepeatTypesingle-2]
}

const _RepeatType_name = "pauserepeatsingle"

var _RepeatType_index = [...]uint8{0, 5, 11, 17}

func (i RepeatType) String() string {
	if i < 0 || i >= RepeatType(len(_RepeatType_index)-1) {
		return "RepeatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepeatType_name[_RepeatType_index[i]:_RepeatType_index[i+1]]
}
